<?php

return [

    '@meta' => [

        'language' => 'Ελληνικά',
        'author'   => 'Christos Chiotis',

        'date' => [
            'shortdays'   => ['Δευ', 'Τρι', 'Τετ', 'Πεμ', 'Παρ', 'Σαβ', 'Κυρ'],
            'longdays'    => ['Δευτέρα', 'Τρίτη', 'Τετάρτη', 'Πέμπτη', 'Παρασκευή', 'Σαββατο', 'Κυριακή'],
            'shortmonths' => ['Ιαν', 'Φεβ', 'Μαρ', 'Απρ', 'Μαι', 'Ιουν', 'Ιουλ', 'Αυγ', 'Σεπ', 'Οκτ', 'Νοε', 'Δεκ'],
            'longmonths'  => ['Ιανουάριος', 'Φεβρουάριος', 'Μαρτιος', 'Απρίλιος', 'Μάιος', 'Ιούνιος', 'Ιούλιος', 'Αύγουστος', 'Σεπτέμβριος', 'Οκτώβριος', 'Νοέμβριος', 'Δεκέμβριος']
        ]
    ],


    // Common
    'Dashboard' => 'Πίνακας Ελέγχου',
    'General' => 'Γενικά',
    'Settings' => 'Ρυθμίσεις',
    'Logout' => 'Αποσύνδεση',
    'Info' => 'Πληροφορίες',
    'Filter by name...' => '',
    'Save' => 'Αποθήκευση',
    'Cancel' => 'Ακύρωση',
    'Entry' => 'Καταχώρηση',
    'Entries' => 'Καταχωρήσεις',
    'Field' => 'Πεδίο',
    'Fields' => 'Πεδία',
    'Date' => 'Ημερομηνία',
    'Latest' => 'Τελευταία',
    'Created' => 'Δημιουργήθηκε',
    'Modified' => 'Επεξεργάστηκε',
    'Today' => 'Σήμερα',
    'Info' => 'Πληροφορίες',
    'Language' => 'Γλώσσα',
    'System' => 'Σύστημα',
    'Are you sure?' => 'Είστε σίγουρος',
    'Uuups, something went wrong...' => 'Ωχ, κάτι δε πήγε καλά...',

    // Activity
    'Activity' => 'Δραστηριότητα',
    'No events logged.' => 'Δεν έχουν καταγραφεί συμβάντα.',
    '%s logged in' => 'συμβάντα καταγράφηκαν',

    // Search
    'Search...'=> 'Αναζήτηση...',
    'Search Results'=> 'Αποτελέσματα αναζήτησης',
    'No results found'=> 'Δεν βρέθηκαν αποτελέσματα',

    // Login
    'Authenticate Please!' => 'Ταυτοποιήστε παρακαλώ!',
    'Authenticate' => 'Ταυτοποίησε',
    'Login failed' => 'Η σύνδεση απέτυχε',
    'Welcome back!' => 'Καλώς ορίσατε!',

    // Accounts
    'Account'  => 'Λογαριασμός',
    'Accounts' => 'Λογοαριασμοί',
    'Name' => 'Όνομα',
    'Username' => 'Όνομα χρήστη',
    'Email' => 'Email',
    'Password' => 'Κωδικός',
    'New Password' => 'Νέος Κωδικός',
    'Create account' => 'Δημιουργία λογαριασμού',
    'Leave the password field empty to keep your current password.' => 'Αφήστε το πεδίο του κωδικού άδειο για να κρατήσετε τον ίδιο κωδικό.',
    'Edit account' => 'Επεξεργασία λογαριασμού',
    'Edit account settings' => 'Επεξεργασία ρυθμίσεων λογαριασμού',
    'Delete account' => 'Διαγραφή λογαριασμού',
    'Account saved!' => 'Ο λογαριασμός αποθηκεύτηκε',
    'Account removed' => 'Ο λογαριασμός διαγράφηκε',
    'You can\'t delete yourself!' => 'Δεν μπορείτε να σβήσετε τον δικό σας λογαριασμό!',
    'You can\'t delete admin accounts!' => 'Δεν μπορείτε να σβήσετε λογαριασμούς με δικαιώματα διαχειριστή!',

    'Groups' => 'Ομάδες Χρηστών',
    'Group' => 'Ομάδα Χρηστών',
    'Manage account groups and permissions' => 'Επεξεργαστείτε ομάδες χρηστών και τα δικαιώματά τους',
    'Add group' => 'Προσθήκη ομάδας',
    'Please enter a groupname' => 'Παρακαλώ εισάγετε ένα όνομα ομάδας',
    'Group saved!' => 'Η ομάδα αποθηκεύτηκε!',
    'Group removed!' => 'Η ομάδα διαγράφηκε',
    'Access' => 'Πρόσβαση',
    'Media root path' => 'Media root path',
    'Relative to' => 'Σχέτικό με',

    // Settings
    'API' => 'API',
    'Registry' => 'Μητρώο',
    'Token' => 'Token',
    'You have no api token generated yet.' => 'Δεν έχετε δημιουργήσει ακόμη API Token.',
    'Generate api token' => 'Δημιουργήστε API Token',
    'The registry is just a global key/value storage you can reuse as global options for your app or site.' => 'Το μητρώο είναι ένα γενικό σημείο αποθήκευσης κλειδιών/τιμών τα οποία μπορείτε να χρησιμοποιήσετε σε οποιοδήποτε σημείο της εφαρμογής ή της ιστοσελίδας ασς.',
    'The registry is empty.' => 'Το μητρώο είναι άδειο.',
    'Access the registry values' => 'Πρόσβαση στις καταχωρήσεις του μητρώου',

    // Addons
    'Addons' => 'Πρόσθετα',
    'No additional addons installed.' => 'Δεν έχουν εγκατασταθεί πρόσθετα.',

    // Collections
    'Collections' => 'Συλλογές',
    'Collection' => 'Συλλογή',
    'Show entries' => 'Δείτε καταχωρήσεις',
    'Create new entry' => 'Δημιουργία νέας',
    'Add collection' => 'Προσθήκη συλλογής',
    'Edit collection' => 'Επεξεργασία συλλογής',
    'Delete collection' => 'Διαγραφή συλλογής',
    'You don\'t have any collections created.' => '',
    'Create a collection' => '',
    'Save Collection' => '',
    'It seems you don\'t have any entries created.' => '',
    'Field name' => '',
    'Add entry' => '',
    'Edit entry' => '',
    'Delete entry' => '',
    'Filter entries...' => '',
    'Reset filter' => '',
    'No entries found.' => '',
    'This field is required.' => '',
    'It seems you don\'t have any fields created.' => '',
    'Field name' => '',
    'Field type' => '',
    'options...' => '',
    'Code syntax' => '',
    'default value...' => '',
    'Required' => '',
    'Separate different options by comma' => '',
    'Goto entries' => '',
    'Fields on entries list page' => '',
    'Order entries on list page' => '',
    'created' => '',
    'modified' => '',
    'descending' => '',
    'ascending' => '',
    'Collection removed' => '',
    'Collection saved!' => '',
    'Entry removed' => '',
    'Entry saved!' => '',
    'Load more...' => '',

    // Mediamanager
    'Mediamanager' => '',
    'Bookmarks' => '',
    'Folders' => '',
    'Folder' => '',
    'Files' => '',
    'File' => '',
    'Upload files' => '',
    'You have nothing bookmarked.' => '',
    'Table mode' => '',
    'List mode' => '',
    'Folders hidden via filter' => '',
    'Files hidden via filter' => '',
    'All' => '',
    'Show files + directories' => '',
    'Show only directories' => '',
    'Show only files' => '',
    'Bookmark folder' => '',
    'Rename folder' => '',
    'Delete folder' => '',
    'Bookmark file' => '',
    'Rename file' => '',
    'Delete file' => '',
    'Download file' => '',
    'Size' => '',
    'Last modified' => '',
    'This folder is empty.' => '',
    'File(s) uploaded.' => '',
    'Save file' => '',
    'Close file' => '',
    'Do you really want to remove %s ?' => '',
    'This file is not writable!' => '',
    'Please enter new name:' => '',
    'Please enter name:' => '',
    '%s is already bookmarked.' => '',
    '%s bookmarked.' => '',
    'Do you really want to remove %s ?' => '',
    'Please enter a name:' => '',
    'Please enter a filename:' => '',
    'Nothing selected' => '',
    'Find files...' => '',

    // Regions
    'Regions' => '',
    'Region' => '',
    'Add region' => '',
    'Create a region' => '',
    'Create groups to organize your regions.' => '',
    'Group name' => 'Naam groep',
    'Groups updated' => 'Groepen gewijzigd',
    'All regions' => '',
    'Edit region' => '',
    'Delete region' => '',
    'You don\'t have any regions created.' => '',
    'Form' => '',
    'Template' => '',
    'Region fields' => '',
    'Form fields' => '',
    'Manage form' => '',
    'Done' => '',
    'This region has no fields yet.' => '',
    'Add field' => '',
    'Insert form field' => '',
    'You have no fields added.' => '',
    'Embed region snippet' => '',
    'Save Region' => '',
    'Region removed' => '',
    'Region saved!' => '',

    // Versions
    'Versions' => '',
    'Version' => '',
    'Restore this version' => '',
    'Clear version history' => '',
    'Close versions' => '',
    'Restoring version...' => '',
    'Version history cleared!' => '',

    // Backups
    'Backups' => '',
    'You don\'t have any backups created.' => '',
    'Create a new backup' => '',
    'Backups are located here' => '',
    'Download backup' => '',
    'Delete backup' => '',
    'Creating backup...' => '',
    'Backup created' => '',
    'Backup deleted' => '',

    // Forms
    'Forms' => 'Φόρμες',
    'Form' => 'Φόρμα',
    'Add form' => 'Προσθήκη φόρμας',
    'Create a form' => 'Δημιουργία φόρμας',
    'Edit form' => 'Επεξεργασία φόρμας',
    'Delete form' => 'Διαγραφή φόρμας',
    'You don\'t have any forms created.' => 'Δεν έχετε δημιουργήσει κάποια φόρμα.',
    'Email form data to this adress' => 'Στείλε με Email τις καταχωρήσεις αυτής της φόρμας στην εξής διεύθυνση',
    'Leave the field empty if you don\'t want to recieve any form data via email.' => 'Αφήστε το πεδίο του email κενό στην περίπτωση που δεν θέλετε να απόστέλονται email κάθε φορά που κάποιος συμπληρώνει την φόρμα.',
    'Save form data' => 'Αποθήκευση των δεδομένων της φόρμας',
    'Save form' => 'Αποθήκευση φόρμας',
    'Form snippet example' => 'Παράδειγμα κώδικα φόρμας',
    'It is important to prefix the form fields with <strong>form[...]</strong>.' => 'Είναι σημαντικό να προσθέσετε στην αρχή κάθε πεδίου φόρμας το <strong>form[...]</strong>',
    'It seems you don\'t have any form entries.' => 'Δεν έχει καταχωρηθεί κάποια απάντηση στην φόρμα σας.',
    'Form data' => 'Δεδομένα φόρμας',

    // Galleries
    'Galleries' => '',
    'Gallery' => '',
    'You don\'t have any galleries created.' => '',
    'All galleries' => '',
    'Add gallery' => '',
    'Create a gallery' => '',
    'Edit gallery' => '',
    'Delete gallery' => '',
    'Gallery saved!' => '',
    'Gallery removed' => '',
    'Select single image' => '',
    'Import images from folder' => '',
    'Import images from folder' => '',
    'No images.' => '',
    'You don\'t have any images in this gallery.' => '',
    'Meta fields' => '',
    'No meta fields defined.' => '',
    'Save gallery' => '',
    '%s image(s) imported' => '',
    'Create groups to organize your galleries.' => '',
    'Create new group' => ''
    
];
