<?php

return [

    '@meta' => [

        'language' => 'Hrvatski',
        'author'   => 'Siniša Perović',

        'date' => [
            'shortdays'   => ['Pon', 'Uto', 'Sri', 'Čet', 'Pet', 'Sub', 'Ned'],
            'longdays'    => ['Ponedjeljak', 'Utorak', 'Srijeda', 'Četvrtak', 'Petak', 'Subota', 'Nedjelja'],
            'shortmonths' => ['Sij', 'Vel', 'Ožu', 'Tra', 'Svi', 'Lip', 'Srp', 'Kol', 'Ruj', 'Lis', 'Stu', 'Pro'],
            'longmonths'  => ['Siječanj', 'Veljača', 'Ožujak', 'Travanj', 'Svibanj', 'Lipanj', 'Srpanj', 'Kolovoz', 'Rujan', 'Listopad', 'Studeni', 'Prosinac']
        ]
    ],



    // Common
    'Dashboard' => 'Kontrolna ploča',
    'General' => 'Sustav',
    'Settings' => 'Postavke',
    'Logout' => 'Odjava',
    'Info' => 'Info',
    'Filter by name...' => 'Filter prema imenu...',
    'Save' => 'Spremi',
    'Cancel' => 'Prekini',
    'Entry' => 'Unos',
    'Entries' => 'Unosa',
    'Field' => 'Polje',
    'Fields' => 'Polja',
    'Date' => 'Datum',
    'Latest' => 'Posljednji',
    'Created' => 'Napravljen',
    'Modified' => 'Mijenjan',
    'Today' => 'Danas',
    'Info' => 'Info',
    'Language' => 'Jezik',
    'System' => 'Sustav',
    'Are you sure?' => 'Sigurno?',

    // Search
    'Search...'=> 'Pretraga...',
    'Search Results'=> 'Rezultati pretrage',
    'No results found'=> 'Nema rezultata pretrage',

    // Login
    'Authenticate Please!' => 'Prijavi se',
    'Authenticate' => 'Prijava',
    'Login failed' => 'Neuspjela prijava',

    // Accounts
    'Account'  => 'Račun',
    'Accounts' => 'Računi',
    'Name' => 'Ime',
    'Username' => 'Korisničko ime',
    'Email' => 'Email',
    'Password' => 'Lozinka',
    'New Password' => 'Nova lozinka',
    'Create account' => 'Napravi račun',
    'Leave the password field empty to keep your current password.' => 'Ostavi prazno ako ne želiš mijenjati lozinku',
    'Edit account' => 'Uredi račun',
    'Edit account settings' => 'Uredi postavke računa',
    'Delete account' => 'Obriši račun',
    'Account saved!' => 'Račun spremljen',

    'Groups' => 'Grupe',
    'Group' => 'Grupa',
    'Manage account groups and permissions' => 'Upravljanje grupama i dozvolama računa',
    'Add group' => 'Dodaj grupu',

    // Addons
    'Addons' => 'Dodaci',
    'No additional addons installed.' => 'Nema instaliranih dodataka',

    // Collections
    'Collections' => 'Kolekcije',
    'Collection' => 'Kolekcija',
    'Show entries' => 'Prikaži unose',
    'Create new entry' => 'Napravi unos',
    'Add collection' => 'Dodaj kolekciju',
    'Edit collection' => 'Uredi kolekciju',
    'Delete collection' => 'Obriši kolekciju',
    'You don\'t have any collections created.' => 'Ne postoje napravljene kolekcije',
    'Save Collection' => 'Spremi kolekciju',
    'It seems you don\'t have any entries created.' => 'Ne postoje napravljeni unosi',
    'Add entry' => 'Dodaj unos',
    'Edit entry' => 'Uredi unos',
    'Delete entry' => 'Obriši unos',
    'This field is required.' => 'Ovo polje je obavezno',
    'It seems you don\'t have any fields created.' => 'Ne postoje napravljena polja',
    'Goto entries' => 'Unosi',
    'Fields on entries list page' => 'Polja na popisu unosa',
    'Order entries on list page' => 'Prikaz popisa unosa',
    'created' => 'Napravljen',
    'modified' => 'Mijenjan',
    'descending' => 'Silazno',
    'ascending' => 'Uzlazno',
    'Collection removed' => 'Kolekcija maknuta',
    'Collection saved!' => 'Kolekcija spremljena',
    'Entry removed' => 'Unos maknut',
    'Entry saved!' => 'Unos spremljen',

    // Mediamanager
    'Mediamanager' => 'Upravitelj datoteka',
    'Bookmarks' => 'Oznake',
    'Folders' => 'Mape',
    'Folder' => 'Mapa',
    'Files' => 'Datoteke',
    'File' => 'Datoteka',
    'You have nothing bookmarked.' => 'Ne postoje oznake',
    'Table mode' => 'Tablica',
    'List mode' => 'Mreža',
    'Folders hidden via filter' => 'Mape sakrivene filterom',
    'Files hidden via filter' => 'Datoteke sakrivene filterom',
    'All' => 'Sve',
    'Show files + directories' => 'Prikaži datoteke i mape',
    'Show only directories' => 'Prikaži samo mape',
    'Show only files' => 'Prikaži samo datoteke',
    'Bookmark folder' => 'Dodaj mapu u oznake',
    'Rename folder' => 'Promjeni ime mape',
    'Delete folder' => 'Obriši mapu',
    'Bookmark file' => 'Dodaj datoteku u oznake',
    'Rename file' => 'Promijeni ime datoteke',
    'Delete file' => 'Obriši datoteku',
    'Download file' => 'Preuzmi datoteku',
    'Size' => 'Veličina',
    'Last modified' => 'Zadnje izmjene',
    'This folder is empty.' => 'Ova mapa je prazna',
    'Save file' => 'Spremi datoteku',
    'Close file' => 'Zatvori datoteku',
    'Do you really want to remove %s ?' => 'Sigurno želiš maknuti %s?',
    'This file is not writable!' => 'Ova datoteka nije za pisanje',
    'Please enter new name:' => 'Unesi novo ime:',
    'Please enter name:' => 'Unesi ime:',
    '%s is already bookmarked.' => '%s je već u oznakama',
    '%s bookmarked.' => '%s dodan u oznake',
    'Do you really want to remove %s ?' => 'Sigurno želiš maknuti %s?',

    // Regions
    'Regions' => 'Odsječci',
    'Region' => 'Odsječak',
    'Add region' => 'Dodaj odsječak',
    'Create a region' => 'Napravi odsječak',
    'Edit region' => 'Uredi odsječak',
    'Delete region' => 'Obriši odsječak',
    'You don\'t have any regions created.' => 'Ne postoje napravljeni odsječci',
    'Form' => 'Obrazac',
    'Template' => 'Predložak',
    'Region fields' => 'Polja odsječka',
    'Form fields' => 'Polja obrasca',
    'Manage form' => 'Upravljanje obrascima',
    'Done' => 'Završetak',
    'This region has no fields yet.' => 'Ovaj odsječak nema polja',
    'Add field' => 'Dodaj polje',
    'Insert form field' => 'Umetni polje obrasca',
    'You have no fields added.' => 'Nema dodanih polja',
    'Embed region snippet' => 'Ugradi \'snippet\' odsječka',
    'Save Region' => 'Spremi odsječak',
    'Region removed' => 'Odsječak maknut',
    'Region saved!' => 'Odsječak spremljen',

    // Versions
    'Versions' => 'Verzije',
    'Version' => 'Verzija',
    'Restore this version' => 'Vrati ovu verziju',
    'Clear version history' => 'Obriši povijest verzija',
    'Close versions' => 'Zatvori verzije',
    'Restoring version...' => 'Vraćanje verzije...',
    'Version history cleared!' => 'Povijest verzija obrisana!',

    // Backups
    'Backups' => 'Sigurnosne kopije',
    'You don\'t have any backups created.' => 'Ne postoje sigurnosne kopije',
    'Create a new backup' => 'Napravi novu kopiju',
    'Backups are located here' => 'Kopije se nalazi ovdje',
    'Download backup' => 'Preuzmi kopiju',
    'Delete backup' => 'Obriši kopiju',
    'Creating backup...' => 'Radim kopiju...',
    'Backup created' => 'Kopija napravljena',
    'Backup deleted' => 'Kopija obrisana',

    // Forms
    'Forms' => 'Obrasci',
    'Form' => 'Obrazac',
    'Add form' => 'Dodaj obrazac',
    'Create a form' => 'Napravi obrazac',
    'Edit form' => 'Uredi obrazac',
    'Delete form' => 'Obriši obrazac',
    'You don\'t have any forms created.' => 'Ne postoje napravljeni obrasci',
    'Email form data to this adress' => 'Pošalji podatke sa obrasca na ovu email adresu',
    'Leave the field empty if you don\'t want to recieve any form data via email.' => 'Ostavi prazno ako ne želiš primati obrasce na email',
    'Save form data' => 'Spremi podatke obrasca',
    'Save form' => 'Spremi obrazac',
    'Form snippet example' => 'Primjer \'snippeta\' obrasca',
    'It is important to prefix the form fields with <strong>form[...]</strong>.' => 'Bitno je staviti prefiks ispred polja obrasca <strong>form[...]</strong>.',
    'It seems you don\'t have any form entries.' => 'Ne postoje unesi obrasci',
    'Form data' => 'Podaci obrasca',

    // Galleries

    'Galleries' => 'Galerije',
    'Gallery' => 'Galerija',
    'You don\'t have any galleries created.' => 'Ne postoje napravljene galerije',
    'Add gallerie' => 'Dodaj galeriju',
    'Create a gallery' => 'Napravi galeriju',
    'Edit gallery' => 'Uredi galeriju',
    'Delete gallery' => 'Obriši galeriju',
    'Gallery saved!' => 'Galerija spremljena!',
    'Select single image' => 'Odaberi jednu sliku',
    'Import images from folder' => 'Uvezi sliku iz mape',
    'Import images from folder' => 'Uvezi slike iz mape',
    'No images.' => 'Nema slika',
    'Save gallery' => 'Spremi galeriju',
    '%s image(s) imported' => '%s slika uvezeno',


];
