<?php

return [

    '@meta' => [

        'language' => 'Hungarian',
        'author'   => 'Ferenc Hajdu',

        'date' => [
            'shortdays'   => ['Hé', 'Ke', 'Sze', 'Cs', 'Pé', 'Szo', 'Va'],
            'longdays'    => ['Hétfő', 'Kedd', 'Szerda', 'Csütörtök', 'Péntek', 'Szombat', 'Vasárnap'],
            'shortmonths' => ['Jan', 'Feb', 'Már', 'Ápr', 'Máj', 'Jún', 'Júl', 'Aug', 'Szep', 'Okt', 'Nov', 'Dec'],
            'longmonths'  => ['Január', 'Február', 'Március', 'Április', 'Május', 'Június', 'Július', 'Augusztus', 'Szeptember', 'Október', 'November', 'December']
        ]
    ],


    // Common
    'Authenticate'  => 'Belépés',
    'Welcome back!'  => 'Üdvözöljük !',
    'Dashboard'  => 'Nyitóképernyő',
    'General'  => 'Általános',
    'Settings' => 'Beállítások',
    'Logout'   => 'Kilépés',
    'Info'     => 'Infó',
    'Filter by name...' => 'Szűrés név alapján...',
    'Save' => 'Mentés',
    'Delete'  => 'Törlés',
    'Cancel' => 'Mégsem',
    'Entry' => 'Tétel',
    'Entries' => 'Tétel',
    'Field' => 'Mező',
    'Fields' => 'Mezők',
	'Field name' => 'Mezőnév',
	'Field type' => 'Mezőtípus',
	'Field label' => 'Mezőcímke',
	'Default value' => 'Alapérték',
	'Required' => 'Kötelező',
	'Localize' => 'Nyelvesítés',
	'multiple' => 'többszörös',
    'Date' => 'Dátum',
    'Latest' => 'Legutóbbi',
    'Group' => 'Csoport',
    'No group' => 'Nincs csoport',
    'Modified' => 'Módosítva',
    'Today'  => 'Ma',
    'Info'  => 'Infó',
    'Language' => 'Nyelv',
    'System' => 'Rendszer',
    'Meta fields' => 'Metaadatok',
    'Are you sure?' => 'Biztos benne?',
    'Search...' => 'Keresés...',
    'Activity' => 'Aktivitás',
    '%s logged in' => '%s belépett.',
	'Extra options' => 'Kiegészítő lehetőségek',

    // Login
    'Authenticate Please!' => 'Kérem, lépjen be!',
    'Welcome back!' => 'Üdvözöljük!',
    'Please login by using your auth credentials.' => 'Kérjük, azonosítója segítségével lépjen be.',
    'Authenticate' => 'Belépés',
	'Show' => 'Megjelenítés',
	'Hide' => 'Elrejtés',
    'Login failed' => 'Belépés sikertelen',

    // Accounts
    'Account'  => 'Fiók',
    'Accounts' => 'Fiókok',
    'Name' => 'Név',
    'Username' => 'Felhasználónév',
    'Email' => 'Email',
    'Password' => 'Jelszó',
    'New Password' => 'Új jelszó',
    'Create account' => 'Fiók létrehozása',
    'Leave the password field empty to keep your current password.' => 'A jelszómezőt üresen hagyva a jelenlegi jelszó nem változik.',
    'Edit account' => 'Fiók módosítása',
    'Edit account settings' => 'Fiókbeállítások módosítása',
    'Delete account' => 'Fiók törlése',
    'Account saved!' => 'Fiók mentve!',

    //Groups
    'Group'=>'Csoport',
    'Groups'=>'Csoportok',
    'Add group'=>'Csoport felvétele',
    'Access'=>'Hozzáférés',
    'Manage account groups and permissions' => 'Fiókcsoportok és engedélyek kezelése',
    'Media root path' => 'Média gyökérkönyvtára',

    // Addons
    'Addons'   => 'Kiegészítők',
    'No additional addons installed.' => 'Nincsenek kiegészítők telepítve',

    // Collections
	'All collections' => 'Minden kollekció',
    'Collections' => 'Kollekciók',
    'Collection' => 'Kollekció',
	'Show all collections' => 'Minden kollekció megjelenítése',
    'Show entries' => 'Tételek megjelenítése',
    'Create new entry' => 'Új tétel felvétele',
    'Create a collection' => 'Kollekció létrehozása',
    'Add collection' => 'Kollekció felvétele',
    'Edit collection' => 'Kollekció szerkesztése',
    'Delete collection' => 'Kollekció törlése',
    'You don\'t have any collections created.' => 'Nincs létrehozott kollekció.',
    'Save Collection' => 'Kollekció mentése',
    'Add entry' => 'Tétel felvétele',
    'Edit entry' => 'Tétel szerkesztése',
    'Delete entry' => 'Tétel törlése',
    'It seems you don\'t have any fields created.' => 'Nincs létrehozott mező.',
    'Goto entries' => 'Ugrás a tételekhez',
    'Fields on entries list page' => 'Listaképernyőn felsorolt mezők',
    'Order entries on list page' => 'Listaképernyőn felsorolt mezők sorrendje',
    'created' => 'létrehozva',
    'modified' => 'módosítva',
    'descending' => 'csökkenő',
    'ascending' => 'növekvő',
    'Collection removed' => 'Kollekció törölve',
    'Collection saved!' => 'Kollekció mentve!',
    'Entry removed' => 'Tétel törölve',
    'Entry saved!' => 'Tétel mentve!',
	'Duplicate collection' => 'Kollekció másolása',
	'Related collection' => 'Kapcsolódó kollekció',
	'Filter entries...' => 'Tételek szűrése...',
	'Reset filter' => 'Szűrés törlése',
	'Export data' => 'Adatok exportálása',
	
	// System
	'System' => 'Rendszer',
	'System Information' => 'Rendszerinformáció',
	'General' => 'Általános',
	'Version' => 'Verzió',
	'Cache size' => 'Gyorsítótár mérete',
	'Data size' => 'Adatok mérete',
	'Mailer' => 'Levelező',
	'No mailer settings found.' => 'Levelezési beállítások nem találhatók.',
	'Directories' => 'Könyvtárak',
	'Path' => 'Útvonal',
	
    // Mediamanager

    'Mediamanager' => 'Médiamenedzser',
    'Bookmarks' => 'Kedvencek',
    'Folders' => 'Mappák',
    'Folder' => 'Mappa',
    'Files' => 'Fájlok',
    'File' => 'Fájl',
    'Upload files' => 'Fájlok feltöltése',
    'Find files...' => 'Fájlok keresése...',
    'You have nothing bookmarked.' => 'Nincs mentett kedvence.',
    'Table mode' => 'Listamód',
    'List mode' => 'Táblázatmód',
    'Folders hidden via filter' => 'Szűrővel rejtett mappák',
    'Files hidden via filter' => 'Szűrővel rejtett fájlok',
    'All' => 'Mind',
    'Show files + directories' => 'Fájlok + mappák megjelenítése',
    'Show only directories' => 'Csak mappák megjelenítése',
    'Show only files' => 'Csak fájlok megjelenítése',
    'Bookmark folder' => 'Mappa hozzáadása a kedvencekhez',
    'Rename folder' => 'Mappa átnevezése',
    'Delete folder' => 'Mappa törlése',
    'Bookmark file' => 'Fájl hozzáadása a kedvencekhez',
    'Rename file' => 'Fájl átnevezése',
    'Delete file' => 'Fájl törlése',
    'Download file' => 'Fájl letöltése',
    'Size' => 'Méret',
    'Last modified' => 'Utoljára módosítva',
    'This folder is empty.' => 'Ez a mappa üres.',
    'Save file' => 'Fájl mentése',
    'Close file' => 'Fájl bezárása',
    'Do you really want to remove %s ?' => 'Tényleg törölni akarja a következőt ? %s',
    'This file is not writable!' => 'Ez a fájl nem írható!',
    'Please enter new name:' => 'Kérem, adja meg az új nevet:',
    'Please enter name:' => 'Kérem, adjon meg egy nevet:',
    '%s is already bookmarked.' => '%s már szerepel a kedvencekben.',
    '%s bookmarked.' => '%s hozzáadva a kedvencekhez.',
    'Do you really want to remove %s ?' => 'Tényleg törölni akarja a következőt ? %s',
	'Please enter a filename:' => 'Kérem, adjon meg egy fájlnevet:',
	'Please enter a name:' => 'Kérem, adjon meg egy nevet:',
	'Change dir to root' => 'ugrás a gyökérkönyvtárba',

    // Regions
    'Regions' => 'Régiók',
    'Region' => 'Régió',
    'Add region' => 'Régió felvétele',
    'Create a region' => 'Régió létrehozása',
    'Edit region' => 'Régió szerkesztése',
    'Delete region' => 'Régió törlése',
    'You don\'t have any regions created.' => 'Nincs létrehozott régió.',
    'Form' => 'Űrlap',
    'Template' => 'Sablon',
    'Region fields' => 'Régiómezők',
    'Form fields' => 'Űrlapmezők',
    'Manage form' => 'Form kezelése',
    'Done' => 'Kész',
    'This region has no fields yet.' => 'A régiónak még nincsenek mezői.',
    'Add field' => 'Mező felvétele',
    'Insert form field' => 'Űrlapmező beszúrása',
    'You have no fields added.' => 'Nincsenek felvett mezők.',
    'Embed region snippet' => 'Régiókódrészlet beágyazása',
    'Save Region' => 'Régió mentése',
    'Region removed' => 'Régió törölve',
    'Region saved!' => 'Régió mentve!',
	'Versions' => 'Verziók',
	'All regions' => 'Minden régió',

    // Backups
    'Backups' => 'Mentések',
    'You don\'t have any backups created.' => 'Nincsenek mentések',
    'Create a new backup' => 'Új mentés létrehozása',
    'Backups are located here' => 'A mentések itt találhatók',
    'Download backup' => 'Mentés letöltése',
    'Delete backup' => 'Mentés törlése',
    'Creating backup...' => 'Mentés létrehozása...',
    'Backup created' => 'Mentés létrehozva',
    'Backup deleted' => 'Mentés törölve',

    // Forms
    'Forms' => 'Űrlapok',
    'Form' => 'Űrlap',
    'Add form' => 'Űrlap felvétele',
    'Show all forms' => 'Minden űrlap megjelenítése',
    'Create a form' => 'Űrlap létrehozása',
    'Edit form' => 'Űrlap szerkesztése',
    'Delete form' => 'Űrlap törlése',
    'You don\'t have any forms created.' => 'Nincs létrehozott űrlap.',
    'Form' => 'Űrlap',
    'Template' => 'Sablon',
    'Form fields' => 'Űrlapmezők',
    'Form fields' => 'Űrlapmezők',
    'Manage form' => 'Űrlap kezelése',
    'Done' => 'Kész',
    'This form has no fields yet.' => 'Az űrlapnak még nincsenek mezői.',
    'Add field' => 'Mező felvétele',
    'Insert form field' => 'Űrlapmező beszúrása',
    'You have no fields added.' => 'Nincsenek felvett mezők.',
    'Embed form snippet' => 'Űrlapkódrészlet beágyazása',
    'Save form' => 'Űrlap mentése',
    'Save form data' => 'Űrlapadatok mentése',
    'Form removed' => 'Űrlap törölve',
    'Form saved!' => 'Űrlap mentve!',
    'Email form data to this adress' => 'Űrlap elküldése erre az emailcímre',
    'Leave the email field empty if you don\'t want to recieve any form data via email.' => 'Hagyja üresen a mezőt, ha nem kívánja emailben megkapni az űrlapadatokat.',	
    'It is important to prefix the form fields with %s .' => 'Fontos, hogy az űrlapmezők %s karaktersorozattal kezdődjenek.',
	'Form snippet example' => 'Űrlapkódrészlet példa',

    //API Settings
    'You have no api token generated yet.' => 'Nincsenek generált API tokenek.',
    'Generate api token' => 'API token generálása',


     // Galleries
    'Galleries' => 'Galériák',
    'Gallery' => 'Galéria',
    'Add gallery' => 'Galéria felvétele',
    'All galleries' => 'Minden galéria',
    'Create groups to organize your galleries.' => 'Csoportok létrehozásával rendszerezheti galériáit.',
    'Create new group' => 'Új csoport létrehozása',
    'Show all galleries' => 'Minden galéria megjelenítése',
    'Create a gallery' => 'Galéria létrehozása',
    'Edit gallery' => 'Galéria szerkesztése',
    'Delete gallery' => 'Galéria törlése',
    'You don\'t have any galleries created.' => 'Nincs létrehozott galéria.',
    'Gallery' => 'Galéria',
    'Template' => 'Sablon',
    'Manage gallery' => 'Galéria kezelése',
    'Done' => 'Kész',
    'This gallery has no fields yet.' => 'A galériának még nincsenek mezői.',
    'Add images to gallery' => 'Képek hozzáadása a galériához',
    'Single image' => 'Egy kép',
    'Images from folder' => 'Képek egy mappából',
    '%s image(s) imported' => '%s kép importálva',
    'Insert gallery field' => 'Galériamező beszúrása',
    'You have no fields added.' => 'Nincsenek felvett mezők.',
    'Embed gallery snippet' => 'Galéria-kódrészlet beágyazása',
    'Save gallery' => 'Galéria mentése',
    'Save gallery data' => 'Galériaadatok mentése',
    'Gallery removed' => 'Galéria törölve',
    'Gallery saved!' => 'Galéria mentve!',
    'You don\'t have any images in this gallery.'=>'Nincsenek képek a galériában.',
	
	// Datastore
	'Datastore' => 'Adattár',
	'No tables yet.' => 'Nincsenek táblák.',
	'Create a table' => 'Tábla létrehozása',
	'Add table' => 'Tábla felvétele',
	'No Entries' => 'Nincsenek tételek',
];
